version: '2'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ../Backend
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - ../Backend:/usr/src
      - /usr/src/node_modules